apiVersion: v1
kind: ConfigMap
metadata:
  name: rancher-config
  labels: {{ include "rancher.labels" . | nindent 4 }}
data:
  priorityClassName:  {{ .Values.priorityClassName }}
  pspEnablement: '{{ .Values.global.cattle.psp.enabled }}'
